version: '3.8'

services:
  # Service 1: The Database
  db:
    image: postgres:15
    container_name: jira_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: minijira
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service 2: Your API
  api:
    build: .
    container_name: jira_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:securepassword@db:5432/minijira
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data: